# for main.py/ood_test.py/ood_train.py
# lenet
LeNet:
  model: LeNet

  dataset: mnist
  augment: true

  epoch: 100
  batch_size: 64

  optimizer: SGD
  lr: 0.001
  weight_decay: 0
  momentum: 0.9
  scheduler: MultiStepLR
  milestones: [50, 75]
  gamma: 0.1


# resnet18
ResNet18:
  model: ResNet18

  dataset: cifar10
  augment: true

  epoch: 100
  batch_size: 64

  optimizer: SGD
  lr: 0.1
  weight_decay: 0.0005
  momentum: 0.9
  scheduler: MultiStepLR
  milestones: [50, 75, 90]
  gamma: 0.1

# resnet34
ResNet34:
  model: ResNet34

  dataset: cifar10
  augment: true

  epoch: 200
  batch_size: 64

  optimizer: SGD
  lr: 0.1
  weight_decay: 0.0005
  momentum: 0.9
  scheduler: MultiStepLR
  milestones: [100, 150, 200]
  gamma: 0.1

# densenet
DenseNet:
  model: DenseNet

  dataset: cifar10
  augment: true

  epoch: 200
  batch_size: 64

  optimizer: SGD
  lr: 0.1
  weight_decay: 0.0001
  momentum: 0.9
  scheduler: MultiStepLR
  milestones: [100, 150]
  gamma: 0.1

# fractalnet
FractalNet:
  model: FractalNet

  dataset: cifar10
  augment: true

  epoch: 200
  batch_size: 64

  optimizer: SGD
  lr: 0.1
  weight_decay: 0.0001
  momentum: 0.9
  scheduler: MultiStepLR
  milestones: [100, 150, 175, 187, 193, 196, 198, 199]
  gamma: 0.1

# vit
ViT:
  model: ViT

  dataset: cifar10
  augment: true

  epoch: 200
  batch_size: 64

  optimizer: Adam
  lr: 0.0001
  weight_decay: null
  momentum: null
  scheduler: CosineAnnealingLR
  milestones: null
  gamma: null

# mlpmixer
MLPMixer:
  model: MLPMixer

  dataset: cifar10
  augment: true

  epoch: 200
  batch_size: 64

  optimizer: Adam
  lr: 0.001
  weight_decay: null
  momentum: null
  scheduler: CosineAnnealingLR
  milestones: null
  gamma: null

# convmixer
ConvMixer:
  model: ConvMixer

  dataset: cifar10
  augment: true

  epoch: 200
  batch_size: 64

  optimizer: Adam
  lr: 0.001
  weight_decay: null
  momentum: null
  scheduler: CosineAnnealingLR
  milestones: null
  gamma: null

# csiresnet18
CSIResNet18:
  model: CSIResNet18

  dataset: cifar10
  augment: true

  epoch: 200
  batch_size: 64

  optimizer: Adam
  lr: 0.001
  weight_decay: null
  momentum: null
  scheduler: CosineAnnealingLR
  milestones: null
  gamma: null


# for ood_test.py/ood_train.py
ood_config:
  variant: 18-pre
  id_dataset: cifar10
  oe_dataset: null
  ood_dataset: svhn
  method: msp
  csi: false
