# for main.py/ood_test.py/ood_train.py
general:
  model: "ResNet18"
  dataset: "CIFAR10"
  augment: True
  epoch: 100
  batch_size: 64

# for ood_test.py/ood_train.py
train:
  variant: None
  id_dataset: None
  oe_dataset: None
  ood_dataset: None
  method: None
